package me.rhunk.snapenhance.common.ui.theme.palettes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import me.rhunk.snapenhance.common.data.theme.AppPalette

/**
 * Colors for Green Apple theme
 * Original color scheme by CarlosEsco, Jays2Kings and CrepeTF
 * M3 colors generated by Material Theme Builder (https://goo.gle/material-theme-builder-web)
 *
 * Key colors:
 * Primary #188140
 * Secondary #188140
 * Tertiary #D33131
 * Neutral #5D5F5B
 */
private val primaryLight = Color(0xFF005927)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFF188140)
private val onPrimaryContainerLight = Color(0xFFFFFFFF)
private val secondaryLight = Color(0xFF005927)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFF97f7a9)
private val onSecondaryContainerLight = Color(0xFF000000)
private val tertiaryLight = Color(0xFF9D0012)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFFD33131)
private val onTertiaryContainerLight = Color(0xFFFFFFFF)
private val errorLight = Color(0xFFBA1A1A)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD6)
private val onErrorContainerLight = Color(0xFF410002)
private val backgroundLight = Color(0xFFF6FBF2)
private val onBackgroundLight = Color(0xFF181D18)
private val surfaceLight = Color(0xFFF6FBF2)
private val onSurfaceLight = Color(0xFF181D18)
private val surfaceVariantLight = Color(0xFFDAE6D7)
private val onSurfaceVariantLight = Color(0xFF3F493F)
private val outlineLight = Color(0xFF6F7A6E)
private val outlineVariantLight = Color(0xFFBECABC)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF2C322C)
private val inverseOnSurfaceLight = Color(0xFFEDF2E9)
private val inversePrimaryLight = Color(0xFF7ADB8F)
private val surfaceDimLight = Color(0xFFD6DCD3)
private val surfaceBrightLight = Color(0xFFF6FBF2)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFF0F5EC)
private val surfaceContainerLight = Color(0xFFEAEFE6)
private val surfaceContainerHighLight = Color(0xFFE4EAE1)
private val surfaceContainerHighestLight = Color(0xFFDFE4DB)

private val primaryDark = Color(0xFF7ADB8F)
private val onPrimaryDark = Color(0xFF003917)
private val primaryContainerDark = Color(0xFF017737)
private val onPrimaryContainerDark = Color(0xFFFFFFFF)
private val secondaryDark = Color(0xFF7ADB8F)
private val onSecondaryDark = Color(0xFF003917)
private val secondaryContainerDark = Color(0xFF017737)
private val onSecondaryContainerDark = Color(0xFFFFFFFF)
private val tertiaryDark = Color(0xFFFFB3AC)
private val onTertiaryDark = Color(0xFF680008)
private val tertiaryContainerDark = Color(0xFFC7282A)
private val onTertiaryContainerDark = Color(0xFFFFFFFF)
private val errorDark = Color(0xFFFFB4AB)
private val onErrorDark = Color(0xFF690005)
private val errorContainerDark = Color(0xFF93000A)
private val onErrorContainerDark = Color(0xFFFFDAD6)
private val backgroundDark = Color(0xFF0F1510)
private val onBackgroundDark = Color(0xFFDFE4DB)
private val surfaceDark = Color(0xFF0F1510)
private val onSurfaceDark = Color(0xFFDFE4DB)
private val surfaceVariantDark = Color(0xFF3F493F)
private val onSurfaceVariantDark = Color(0xFFBECABC)
private val outlineDark = Color(0xFF889487)
private val outlineVariantDark = Color(0xFF3F493F)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFDFE4DB)
private val inverseOnSurfaceDark = Color(0xFF2C322C)
private val inversePrimaryDark = Color(0xFF006D32)
private val surfaceDimDark = Color(0xFF0F1510)
private val surfaceBrightDark = Color(0xFF353B35)
private val surfaceContainerLowestDark = Color(0xFF0A0F0B)
private val surfaceContainerLowDark = Color(0xFF181D18)
private val surfaceContainerDark = Color(0xFF1C211C)
private val surfaceContainerHighDark = Color(0xFF262B26)
private val surfaceContainerHighestDark = Color(0xFF313630)

val GreenApple = AppPalette(
    key = "green_apple",
    lightColors = lightColorScheme(
        primary = primaryLight,
        onPrimary = onPrimaryLight,
        primaryContainer = primaryContainerLight,
        onPrimaryContainer = onPrimaryContainerLight,
        secondary = secondaryLight,
        onSecondary = onSecondaryLight,
        secondaryContainer = secondaryContainerLight,
        onSecondaryContainer = onSecondaryContainerLight,
        tertiary = tertiaryLight,
        onTertiary = onTertiaryLight,
        tertiaryContainer = tertiaryContainerLight,
        onTertiaryContainer = onTertiaryContainerLight,
        error = errorLight,
        onError = onErrorLight,
        errorContainer = errorContainerLight,
        onErrorContainer = onErrorContainerLight,
        background = backgroundLight,
        onBackground = onBackgroundLight,
        surface = surfaceLight,
        onSurface = onSurfaceLight,
        surfaceVariant = surfaceVariantLight,
        onSurfaceVariant = onSurfaceVariantLight,
        outline = outlineLight,
        outlineVariant = outlineVariantLight,
        scrim = scrimLight,
        inverseSurface = inverseSurfaceLight,
        inverseOnSurface = inverseOnSurfaceLight,
        inversePrimary = inversePrimaryLight,
        surfaceDim = surfaceDimLight,
        surfaceBright = surfaceBrightLight,
        surfaceContainerLowest = surfaceContainerLowestLight,
        surfaceContainerLow = surfaceContainerLowLight,
        surfaceContainer = surfaceContainerLight,
        surfaceContainerHigh = surfaceContainerHighLight,
        surfaceContainerHighest = surfaceContainerHighestLight,
    ),

    darkColors = darkColorScheme(
        primary = primaryDark,
        onPrimary = onPrimaryDark,
        primaryContainer = primaryContainerDark,
        onPrimaryContainer = onPrimaryContainerDark,
        secondary = secondaryDark,
        onSecondary = onSecondaryDark,
        secondaryContainer = secondaryContainerDark,
        onSecondaryContainer = onSecondaryContainerDark,
        tertiary = tertiaryDark,
        onTertiary = onTertiaryDark,
        tertiaryContainer = tertiaryContainerDark,
        onTertiaryContainer = onTertiaryContainerDark,
        error = errorDark,
        onError = onErrorDark,
        errorContainer = errorContainerDark,
        onErrorContainer = onErrorContainerDark,
        background = backgroundDark,
        onBackground = onBackgroundDark,
        surface = surfaceDark,
        onSurface = onSurfaceDark,
        surfaceVariant = surfaceVariantDark,
        onSurfaceVariant = onSurfaceVariantDark,
        outline = outlineDark,
        outlineVariant = outlineVariantDark,
        scrim = scrimDark,
        inverseSurface = inverseSurfaceDark,
        inverseOnSurface = inverseOnSurfaceDark,
        inversePrimary = inversePrimaryDark,
        surfaceDim = surfaceDimDark,
        surfaceBright = surfaceBrightDark,
        surfaceContainerLowest = surfaceContainerLowestDark,
        surfaceContainerLow = surfaceContainerLowDark,
        surfaceContainer = surfaceContainerDark,
        surfaceContainerHigh = surfaceContainerHighDark,
        surfaceContainerHighest = surfaceContainerHighestDark,
    )
)