name: Debug CI
on:
  workflow_dispatch:
      inputs:
        ci_upload:
          description: 'Upload to CI channel'
          required: false
          type: boolean
          
jobs:
  job_armv8:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup NPM Dependencies
        run: npm install typescript -g

      - name: Build
        run: ./gradlew assembleArmv8Debug

      - name: Sign APK
        id: sign_app
        uses: tiann/zipalign-sign-android-release@v1.1.4
        with:
          releaseDirectory: app/build/outputs/apk/armv8/debug/
          signingKeyBase64: ${{ secrets.JAVA_KEYSTORE_DATA }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          zipAlign: true
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Delete unsigned file
        run: |
          cd app/build/outputs/apk/armv8/debug/
          shopt -s extglob
          rm -rf !(*-signed*)
          
      - name: Build Version
        run: ./gradlew getVersion

      - name: Set Environment Variables
        id: version-env
        run: |
          echo "version=$(cat app/build/version.txt)" >> $GITHUB_ENV
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Git branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@main

      - name: Rename APK file
        run: |
          mv app/build/outputs/apk/armv8/debug/*.apk app/build/outputs/apk/armv8/debug/SE-Extended-${{ env.version }}-ARMV8-${{ steps.version-env.outputs.sha_short }}.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SE-Extended-ARMV8-Debug
          path: app/build/outputs/apk/armv8/debug/*.apk
          
  job_armv7:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup NPM Dependencies
        run: npm install typescript -g

      - name: Build
        run: ./gradlew assembleArmv7Debug

      - name: Sign APK
        id: sign_app
        uses: tiann/zipalign-sign-android-release@v1.1.4
        with:
          releaseDirectory: app/build/outputs/apk/armv7/debug/
          signingKeyBase64: ${{ secrets.JAVA_KEYSTORE_DATA }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          zipAlign: true
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Delete unsigned file
        run: |
          cd app/build/outputs/apk/armv7/debug/
          shopt -s extglob
          rm -rf !(*-signed*)
          
      - name: Build Version
        run: ./gradlew getVersion

      - name: Set Environment Variables
        id: version-env
        run: |
          echo "version=$(cat app/build/version.txt)" >> $GITHUB_ENV
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Git branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@main

      - name: Rename APK file
        run: |
          mv app/build/outputs/apk/armv7/debug/*.apk app/build/outputs/apk/armv7/debug/SE-Extended-${{ env.version }}-ARMV7-${{ steps.version-env.outputs.sha_short }}.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SE-Extended-ARMV7-Debug
          path: app/build/outputs/apk/armv7/debug/*.apk

  job_universal:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup NPM Dependencies
        run: npm install typescript -g

      - name: Build
        run: ./gradlew assembleAllDebug

      - name: Sign APK
        id: sign_app
        uses: tiann/zipalign-sign-android-release@v1.1.4
        with:
          releaseDirectory: app/build/outputs/apk/all/debug/
          signingKeyBase64: ${{ secrets.JAVA_KEYSTORE_DATA }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          zipAlign: true
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Delete unsigned file
        run: |
          cd app/build/outputs/apk/all/debug/
          shopt -s extglob
          rm -rf !(*-signed*)
          
      - name: Build Version
        run: ./gradlew getVersion

      - name: Set Environment Variables
        id: version-env
        run: |
          echo "version=$(cat app/build/version.txt)" >> $GITHUB_ENV
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Git branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@main

      - name: Rename APK files
        run: |
          mv app/build/outputs/apk/all/debug/*.apk app/build/outputs/apk/all/debug/SE-Extended-${{ env.version }}-UNIVERSAL-${{ steps.version-env.outputs.sha_short }}.apk

      - name: Upload universal
        uses: actions/upload-artifact@v4
        with:
          name: SE-Extended-UNIVERSAL-Debug
          path: app/build/outputs/apk/all/debug/*.apk

  job_manager:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew manager:assembleDebug

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Manager
          path: manager/build/outputs/apk/debug/*.apk

  job_core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew assembleCoreDebug

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Core
          path: app/build/outputs/apk/core/debug/*.apk
