name: Github Updates
on:
  push:
    branches:
      - dev
  watch:
    types: [started]

jobs:
  build:
    name: Sending Update Message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract Commit Info
        id: info
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "trigger=push" >> $GITHUB_OUTPUT
            COUNT=$(jq '.commits | length' $GITHUB_EVENT_PATH)
            if [ "$COUNT" -eq 1 ]; then
              echo "header=New commit has been pushed to the ${{ github.ref_name }} branch!" >> $GITHUB_OUTPUT
            else
              echo "header=New commits have been pushed to the ${{ github.ref_name }} branch!" >> $GITHUB_OUTPUT
            fi
            {
              echo 'commit_list<<EOF'
              jq -r --arg repo "${{ github.repository }}" '.commits | reverse | .[] | "[#\(.id | .[0:7])](https://github.com/\($repo)/commit/\(.id)) - \(.message | split("\n")[0] | split(" - ")[0])"' $GITHUB_EVENT_PATH
              echo 'EOF'
            } >> $GITHUB_OUTPUT

          elif [[ "${{ github.event_name }}" == "watch" ]]; then
            echo "trigger=watch" >> $GITHUB_OUTPUT
          fi

      - name: Sending Message for Push
        if: steps.info.outputs.trigger == 'push'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            [${{ github.repository }}](https://github.com/${{ github.repository }})

            ${{ steps.info.outputs.header }}
            ${{ steps.info.outputs.commit_list }}

      - name: Sending Message for Watch
        if: steps.info.outputs.trigger == 'watch'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            ⭐ [@${{ github.actor }}](https://github.com/${{ github.actor }}) starred [${{ github.repository }}](https://github.com/${{ github.repository }}).

      - name: Delete previous workflow runs
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          CURRENT_RUN_ID=${{ github.run_id }}
          WORKFLOW_NAME="${{ github.workflow }}"
          WORKFLOW_RUNS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?status=completed")

          if [[ $(echo "$WORKFLOW_RUNS" | jq -e '.workflow_runs != null') == "true" ]]; then
            PREVIOUS_RUN_IDS=$(echo "$WORKFLOW_RUNS" | jq -r ".workflow_runs[] | select(.id != $CURRENT_RUN_ID and .name == \"$WORKFLOW_NAME\") | .id")
            for RUN_ID in $PREVIOUS_RUN_IDS; do
              echo "Deleting run ID: $RUN_ID"
              curl -s -X DELETE -H "Authorization: Bearer $GITHUB_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID"
            done
          fi
