name: Pull Request CI
on:
  pull_request:
    branches: ["dev"]

jobs:
  job_armv8:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew

      - name: Setup NPM Dependencies
        run: npm install typescript -g

      - name: Setup Android targets for Rust
        run: rustup target add armv7-linux-androideabi aarch64-linux-android

      - name: Build
        run: ./gradlew assembleArmv8Debug

      - name: Get Current Build Version
        id: version-env
        run: |
          ./gradlew getVersion
          echo "version=$(cat app/build/version.txt)" >> $GITHUB_ENV

      - name: Rename APK File
        run: |
          mv app/build/outputs/apk/armv8/debug/*.apk app/build/outputs/apk/armv8/debug/SE-Extended-${{ env.version }}-ARMV8-${GITHUB_SHA::7}.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SE-Extended-ARMV8-PR
          path: app/build/outputs/apk/armv8/debug/*.apk
          
  job_armv7:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set Up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew

      - name: Setup NPM Dependencies
        run: npm install typescript -g

      - name: Setup Android targets for Rust
        run: rustup target add armv7-linux-androideabi aarch64-linux-android

      - name: Build
        run: ./gradlew assembleArmv7Debug

      - name: Get Current Build Version
        id: version-env
        run: |
          ./gradlew getVersion
          echo "version=$(cat app/build/version.txt)" >> $GITHUB_ENV

      - name: Rename APK File
        run: |
          mv app/build/outputs/apk/armv7/debug/*.apk app/build/outputs/apk/armv7/debug/SE-Extended-${{ env.version }}-ARMV7-${GITHUB_SHA::7}.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SE-Extended-ARMV7-PR
          path: app/build/outputs/apk/armv7/debug/*.apk

  job_universal:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set Up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew

      - name: Setup NPM Dependencies
        run: npm install typescript -g

      - name: Setup Android targets for Rust
        run: rustup target add armv7-linux-androideabi aarch64-linux-android
        
      - name: Build
        run: ./gradlew assembleAllDebug

      - name: Get Current Build Version
        id: version-env
        run: |
          ./gradlew getVersion
          echo "version=$(cat app/build/version.txt)" >> $GITHUB_ENV

      - name: Rename APK File
        run: |
          mv app/build/outputs/apk/all/debug/*.apk app/build/outputs/apk/all/debug/SE-Extended-${{ env.version }}-UNIVERSAL-${GITHUB_SHA::7}.apk

      - name: Upload Universal
        uses: actions/upload-artifact@v4
        with:
          name: SE-Extended-UNIVERSAL-PR
          path: app/build/outputs/apk/all/debug/*.apk

  job_manager:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set Up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew manager:assembleDebug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Manager
          path: manager/build/outputs/apk/debug/*.apk

  job_core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set Up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew

      - name: Setup Android targets for Rust
        run: rustup target add armv7-linux-androideabi aarch64-linux-android

      - name: Build
        run: ./gradlew assembleCoreDebug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Core
          path: app/build/outputs/apk/core/debug/*.apk
